In [1]:
import pandas as pd
import numpy as np
import torch
from torch import nn
from torch import optim
import torch.nn.functional as F


In [2]:
texts = 'The electrical telegraph systems, developed in the early 19th century, used simple electrical signals to send text messages. In the late 19th century, the wireless telegraphy was developed using radio waves. In 1933, the German Reichspost (Reich postal service) introduced the first "telex" service.\
The University of Hawaii began using radio to send digital information as early as 1971, using ALOHAnet.[citation needed] Friedhelm Hillebrand conceptualised SMS in 1984 while working for Deutsche Telekom. Sitting at a typewriter at home, Hillebrand typed out random sentences and counted every letter, number, punctuation, and space. Almost every time, the messages contained fewer than 160 characters, thus giving the basis for the limit one could type via text messaging.[4] With Bernard Ghillebaert of France Télécom, he developed a proposal for the GSM (Groupe Spécial Mobile) meeting in February 1985 in Oslo.[5] The first technical solution evolved in a GSM subgroup under the leadership of Finn Trosby. It was further developed under the leadership of Kevin Holley and Ian Harris (see Short Message Service).[6] SMS forms an integral part of Signalling System No. 7 (SS7).[7] Under SS7, it is a "state" with a 160 character data, coded in the ITU-T "T.56" text format, that has a "sequence lead in" to determine different language codes and may have special character codes that permit, for example, sending simple graphs as text. This was part of ISDN (Integrated Services Digital Network) and since GSM is based on this, it made its way to the mobile phone. Messages could be sent and received on ISDN phones, and these can send SMS to any GSM phone. The possibility of doing something is one thing, implementing it another, but systems existed from 1988 that sent SMS messages to mobile phones[citation needed] (compare ND-NOTIS).\
SMS messaging was used for the first time on 3 December 1992, when Neil Papworth, a 22-year-old test engineer for Sema Group in the UK[9] (now Airwide Solutions),[10] used a personal computer to send the text message "Merry Christmas" via the Vodafone network to the phone of Richard Jarvis,[11][12] who was at a party in Newbury, Berkshire, which had been organized to celebrate the event. Modern SMS text messaging is usually messaging from one mobile phone to another. Finnish Radiolinja became the first network to offer a commercial person-to-person SMS text messaging service in 1994. When Radiolinjas domestic competitor, Telecom Finland (now part of TeliaSonera) also launched SMS text messaging in 1995 and the two networks offered cross-network SMS functionality, Finland became the first nation where SMS text messaging was offered on a competitive as well as on a commercial basis. GSM was allowed[by whom?] in the United States and the radio frequencies were blocked and awarded to US "Carriers" to use US technology. Hence there is no "development" in the US in mobile messaging service. The GSM in the US had to use a frequency allocated for private communication services (PCS) – what the ITU frequency régime had blocked for DECT – Digital Enhanced Cordless Telecommunications – 1000-feet range picocell, but survived. American Personal Communications (APC), the first GSM carrier in America, provided the first text-messaging service in the United States. Sprint Telecommunications Venture, a partnership of Sprint Corp. and three large cable-TV companies, owned 49 percent of APC. The Sprint venture was the largest single buyer at a government-run spectrum auction that raised $7.7 billion in 2005 for PCS licenses. APC operated under the brand name of Sprint Spectrum and launched its service on 15 November 1995, in Washington, D.C. and in Baltimore, Maryland. Vice President Al Gore in Washington, D.C. made the initial phone-call to launch the network, calling Mayor Kurt Schmoke in Baltimore.[13]\
Initial growth of text messaging[where?] was slow, with customers in 1995 sending on average only 0.4 messages per GSM customer per month.[14] One factor in the slow take-up of SMS was that operators were slow to set up charging systems, especially for prepaid subscribers, and to eliminate billing fraud, which was possible by changing SMSC settings on individual handsets to use the SMSCs of other operators.[citation needed] Over time, this issue was eliminated by switch billing instead of billing at the SMSC and by new features within SMSCs to allow blocking of foreign mobile users sending messages through it.[citation needed] SMS is available on a wide range of networks, including 3G networks. However, not all text-messaging systems use SMS; some notable alternate implementations of the concept include J-Phones SkyMail and NTT Docomos Short Mail, both in Japan. E-mail messaging from phones, as popularized by NTT Docomos i-mode and the RIM BlackBerry, also typically use standard mail protocols such as SMTP over TCP/IP.[15] As of 2007 text messaging was the most widely used mobile data service, with 74% of all mobile phone users worldwide, or 2.4 billion out of 3.3 billion phone subscribers, at the end of 2007 being active users of the Short Message Service. In countries such as Finland, Sweden, and Norway, over 85% of the population use SMS. The European average is about 80%, and North America is rapidly catching up with over 60% active users of SMS by end of 2008.[citation needed] The largest average usage of the service by mobile phone subscribers occurs in the Philippines, with an average of 27 texts sent per day per subscriber.[citation needed]\
Uses[edit]\
A text message on an iPhone announcing an AMBER Alert\
Text messaging is most often used between private mobile phone users, as a substitute for voice calls in situations where voice communication is impossible or undesirable (e.g., during a school class or a work meeting). Texting is also used to communicate very brief messages, such as informing someone that you will be late or reminding a friend or colleague about a meeting. As with e-mail, informality and brevity have become an accepted part of text messaging. Some text messages such as SMS can also be used for the remote control of home appliances. It is widely used in domotics systems. Some amateurs have also built their own systems to control (some of) their appliances via SMS.[16][17] Other methods such as group messaging, which was patented in 2012 by the GM of Andrew Ferry, Devin Peterson, Justin Cowart, Ian Ainsworth, Patrick Messinger, Jacob Delk, Jack Grande, Austin Hughes, Brendan Blake, and Brooks Brasher are used to involve more than two people into a text messaging conversation[citation needed]. A Flash SMS is a type[18] of text message that appears directly on the main screen without user interaction and is not automatically stored in the inbox. It can be useful in cases such as an emergency (e.g., fire alarm) or confidentiality (e.g., one-time password).[19]\
Short message services are developing very rapidly throughout the world. SMS is particularly popular in Europe, Asia (excluding Japan; see below), United States, Australia, and New Zealand and is also gaining influence in Africa. Popularity has grown to a sufficient extent that the term texting (used as a verb meaning the act of mobile phone users sending short messages back and forth) has entered the common lexicon. Young Asians consider SMS as the most popular mobile phone application.[20] Fifty percent of American teens send fifty text messages or more per day, making it their most frequent form of communication.[21] In China, SMS is very popular and has brought service providers significant profit (18 billion short messages were sent in 2001).[22]\
It is a very influential and powerful tool in the Philippines, where the average user sends 10–12 text messages a day. The Philippines alone sends on average over 1 billion text messages a day,[23] more than the annual average SMS volume of the countries in Europe, and even China and India. SMS is hugely popular in India, where youngsters often exchange many text messages, and companies provide alerts, infotainment, news, cricket scores updates, railway/airline booking, mobile billing, and banking services on SMS.\
Similarly, in 2008, text messaging played a primary role in the implication of former Detroit Mayor Kwame Kilpatrick in an SMS sex scandal.[24] Short messages are particularly popular among young urbanites. In many markets, the service is comparatively cheap. For example, in Australia, a message typically costs between A$0.20 and $0.25 to send (some prepaid services charge $0.01 between their own phones), compared with a voice call, which costs somewhere between $0.40 and $2.00 per minute (commonly charged in half-minute blocks). The service is enormously profitable to the service providers. At a typical length of only 190 bytes (including protocol overhead), more than 350 of these messages per minute can be transmitted at the same data rate as a usual voice call (9 kbit/s). There are also free SMS services available, which are often sponsored, that allow sending[25] and receiving[26] SMS from a PC connected to the Internet. Mobile service providers in New Zealand, such as Vodafone and Telecom NZ, provide up to 2000 SMS messages for NZ$10 per month. Users on these plans send on average 1500 SMS messages every month. Text messaging has become so popular that advertising agencies and advertisers are now jumping into the text messaging business. Services that provide bulk text message sending are also becoming a popular way for clubs, associations, and advertisers to reach a group of opt-in subscribers quickly.\
Research suggests that Internet-based mobile messaging will have grown to equal the popularity of SMS in 2013, with nearly 10 trillion messages being sent through each technology.[27][28] Services such as Facebook Messenger, Snapchat, WhatsApp and Viber have led to a decline in the use of SMS in parts of the world.\
Research has shown that women are more likely than men to use emoticons in text messages.[29]\
The electrical telegraph systems, developed in the early 19th century, used simple electrical signals to send text messages. In the late 19th century, the wireless telegraphy was developed using radio waves. In 1933, the German Reichspost (Reich postal service) introduced the first "telex" service.\
The University of Hawaii began using radio to send digital information as early as 1971, using ALOHAnet.[citation needed] Friedhelm Hillebrand conceptualised SMS in 1984 while working for Deutsche Telekom. Sitting at a typewriter at home, Hillebrand typed out random sentences and counted every letter, number, punctuation, and space. Almost every time, the messages contained fewer than 160 characters, thus giving the basis for the limit one could type via text messaging.[4] With Bernard Ghillebaert of France Télécom, he developed a proposal for the GSM (Groupe Spécial Mobile) meeting in February 1985 in Oslo.[5] The first technical solution evolved in a GSM subgroup under the leadership of Finn Trosby. It was further developed under the leadership of Kevin Holley and Ian Harris (see Short Message Service).[6] SMS forms an integral part of Signalling System No. 7 (SS7).[7] Under SS7, it is a "state" with a 160 character data, coded in the ITU-T "T.56" text format, that has a "sequence lead in" to determine different language codes and may have special character codes that permit, for example, sending simple graphs as text. This was part of ISDN (Integrated Services Digital Network) and since GSM is based on this, it made its way to the mobile phone. Messages could be sent and received on ISDN phones, and these can send SMS to any GSM phone. The possibility of doing something is one thing, implementing it another, but systems existed from 1988 that sent SMS messages to mobile phones[citation needed] (compare ND-NOTIS).\
SMS messaging was used for the first time on 3 December 1992, when Neil Papworth, a 22-year-old test engineer for Sema Group in the UK[9] (now Airwide Solutions),[10] used a personal computer to send the text message "Merry Christmas" via the Vodafone network to the phone of Richard Jarvis,[11][12] who was at a party in Newbury, Berkshire, which had been organized to celebrate the event. Modern SMS text messaging is usually messaging from one mobile phone to another. Finnish Radiolinja became the first network to offer a commercial person-to-person SMS text messaging service in 1994. When Radiolinjas domestic competitor, Telecom Finland (now part of TeliaSonera) also launched SMS text messaging in 1995 and the two networks offered cross-network SMS functionality, Finland became the first nation where SMS text messaging was offered on a competitive as well as on a commercial basis. GSM was allowed[by whom?] in the United States and the radio frequencies were blocked and awarded to US "Carriers" to use US technology. Hence there is no "development" in the US in mobile messaging service. The GSM in the US had to use a frequency allocated for private communication services (PCS) – what the ITU frequency régime had blocked for DECT – Digital Enhanced Cordless Telecommunications – 1000-feet range picocell, but survived. American Personal Communications (APC), the first GSM carrier in America, provided the first text-messaging service in the United States. Sprint Telecommunications Venture, a partnership of Sprint Corp. and three large cable-TV companies, owned 49 percent of APC. The Sprint venture was the largest single buyer at a government-run spectrum auction that raised $7.7 billion in 2005 for PCS licenses. APC operated under the brand name of Sprint Spectrum and launched its service on 15 November 1995, in Washington, D.C. and in Baltimore, Maryland. Vice President Al Gore in Washington, D.C. made the initial phone-call to launch the network, calling Mayor Kurt Schmoke in Baltimore.[13]\
Initial growth of text messaging[where?] was slow, with customers in 1995 sending on average only 0.4 messages per GSM customer per month.[14] One factor in the slow take-up of SMS was that operators were slow to set up charging systems, especially for prepaid subscribers, and to eliminate billing fraud, which was possible by changing SMSC settings on individual handsets to use the SMSCs of other operators.[citation needed] Over time, this issue was eliminated by switch billing instead of billing at the SMSC and by new features within SMSCs to allow blocking of foreign mobile users sending messages through it.[citation needed] SMS is available on a wide range of networks, including 3G networks. However, not all text-messaging systems use SMS; some notable alternate implementations of the concept include J-Phones SkyMail and NTT Docomos Short Mail, both in Japan. E-mail messaging from phones, as popularized by NTT Docomos i-mode and the RIM BlackBerry, also typically use standard mail protocols such as SMTP over TCP/IP.[15] As of 2007 text messaging was the most widely used mobile data service, with 74% of all mobile phone users worldwide, or 2.4 billion out of 3.3 billion phone subscribers, at the end of 2007 being active users of the Short Message Service. In countries such as Finland, Sweden, and Norway, over 85% of the population use SMS. The European average is about 80%, and North America is rapidly catching up with over 60% active users of SMS by end of 2008.[citation needed] The largest average usage of the service by mobile phone subscribers occurs in the Philippines, with an average of 27 texts sent per day per subscriber.[citation needed]\
Uses[edit]\
A text message on an iPhone announcing an AMBER Alert\
Text messaging is most often used between private mobile phone users, as a substitute for voice calls in situations where voice communication is impossible or undesirable (e.g., during a school class or a work meeting). Texting is also used to communicate very brief messages, such as informing someone that you will be late or reminding a friend or colleague about a meeting. As with e-mail, informality and brevity have become an accepted part of text messaging. Some text messages such as SMS can also be used for the remote control of home appliances. It is widely used in domotics systems. Some amateurs have also built their own systems to control (some of) their appliances via SMS.[16][17] Other methods such as group messaging, which was patented in 2012 by the GM of Andrew Ferry, Devin Peterson, Justin Cowart, Ian Ainsworth, Patrick Messinger, Jacob Delk, Jack Grande, Austin Hughes, Brendan Blake, and Brooks Brasher are used to involve more than two people into a text messaging conversation[citation needed]. A Flash SMS is a type[18] of text message that appears directly on the main screen without user interaction and is not automatically stored in the inbox. It can be useful in cases such as an emergency (e.g., fire alarm) or confidentiality (e.g., one-time password).[19]\
Short message services are developing very rapidly throughout the world. SMS is particularly popular in Europe, Asia (excluding Japan; see below), United States, Australia, and New Zealand and is also gaining influence in Africa. Popularity has grown to a sufficient extent that the term texting (used as a verb meaning the act of mobile phone users sending short messages back and forth) has entered the common lexicon. Young Asians consider SMS as the most popular mobile phone application.[20] Fifty percent of American teens send fifty text messages or more per day, making it their most frequent form of communication.[21] In China, SMS is very popular and has brought service providers significant profit (18 billion short messages were sent in 2001).[22]\
It is a very influential and powerful tool in the Philippines, where the average user sends 10–12 text messages a day. The Philippines alone sends on average over 1 billion text messages a day,[23] more than the annual average SMS volume of the countries in Europe, and even China and India. SMS is hugely popular in India, where youngsters often exchange many text messages, and companies provide alerts, infotainment, news, cricket scores updates, railway/airline booking, mobile billing, and banking services on SMS.\
Similarly, in 2008, text messaging played a primary role in the implication of former Detroit Mayor Kwame Kilpatrick in an SMS sex scandal.[24] Short messages are particularly popular among young urbanites. In many markets, the service is comparatively cheap. For example, in Australia, a message typically costs between A$0.20 and $0.25 to send (some prepaid services charge $0.01 between their own phones), compared with a voice call, which costs somewhere between $0.40 and $2.00 per minute (commonly charged in half-minute blocks). The service is enormously profitable to the service providers. At a typical length of only 190 bytes (including protocol overhead), more than 350 of these messages per minute can be transmitted at the same data rate as a usual voice call (9 kbit/s). There are also free SMS services available, which are often sponsored, that allow sending[25] and receiving[26] SMS from a PC connected to the Internet. Mobile service providers in New Zealand, such as Vodafone and Telecom NZ, provide up to 2000 SMS messages for NZ$10 per month. Users on these plans send on average 1500 SMS messages every month. Text messaging has become so popular that advertising agencies and advertisers are now jumping into the text messaging business. Services that provide bulk text message sending are also becoming a popular way for clubs, associations, and advertisers to reach a group of opt-in subscribers quickly.\
Research suggests that Internet-based mobile messaging will have grown to equal the popularity of SMS in 2013, with nearly 10 trillion messages being sent through each technology.[27][28] Services such as Facebook Messenger, Snapchat, WhatsApp and Viber have led to a decline in the use of SMS in parts of the world.\
Research has shown that women are more likely than men to use emoticons in text messages.[29]\
The electrical telegraph systems, developed in the early 19th century, used simple electrical signals to send text messages. In the late 19th century, the wireless telegraphy was developed using radio waves. In 1933, the German Reichspost (Reich postal service) introduced the first "telex" service.\
The University of Hawaii began using radio to send digital information as early as 1971, using ALOHAnet.[citation needed] Friedhelm Hillebrand conceptualised SMS in 1984 while working for Deutsche Telekom. Sitting at a typewriter at home, Hillebrand typed out random sentences and counted every letter, number, punctuation, and space. Almost every time, the messages contained fewer than 160 characters, thus giving the basis for the limit one could type via text messaging.[4] With Bernard Ghillebaert of France Télécom, he developed a proposal for the GSM (Groupe Spécial Mobile) meeting in February 1985 in Oslo.[5] The first technical solution evolved in a GSM subgroup under the leadership of Finn Trosby. It was further developed under the leadership of Kevin Holley and Ian Harris (see Short Message Service).[6] SMS forms an integral part of Signalling System No. 7 (SS7).[7] Under SS7, it is a "state" with a 160 character data, coded in the ITU-T "T.56" text format, that has a "sequence lead in" to determine different language codes and may have special character codes that permit, for example, sending simple graphs as text. This was part of ISDN (Integrated Services Digital Network) and since GSM is based on this, it made its way to the mobile phone. Messages could be sent and received on ISDN phones, and these can send SMS to any GSM phone. The possibility of doing something is one thing, implementing it another, but systems existed from 1988 that sent SMS messages to mobile phones[citation needed] (compare ND-NOTIS).\
SMS messaging was used for the first time on 3 December 1992, when Neil Papworth, a 22-year-old test engineer for Sema Group in the UK[9] (now Airwide Solutions),[10] used a personal computer to send the text message "Merry Christmas" via the Vodafone network to the phone of Richard Jarvis,[11][12] who was at a party in Newbury, Berkshire, which had been organized to celebrate the event. Modern SMS text messaging is usually messaging from one mobile phone to another. Finnish Radiolinja became the first network to offer a commercial person-to-person SMS text messaging service in 1994. When Radiolinjas domestic competitor, Telecom Finland (now part of TeliaSonera) also launched SMS text messaging in 1995 and the two networks offered cross-network SMS functionality, Finland became the first nation where SMS text messaging was offered on a competitive as well as on a commercial basis. GSM was allowed[by whom?] in the United States and the radio frequencies were blocked and awarded to US "Carriers" to use US technology. Hence there is no "development" in the US in mobile messaging service. The GSM in the US had to use a frequency allocated for private communication services (PCS) – what the ITU frequency régime had blocked for DECT – Digital Enhanced Cordless Telecommunications – 1000-feet range picocell, but survived. American Personal Communications (APC), the first GSM carrier in America, provided the first text-messaging service in the United States. Sprint Telecommunications Venture, a partnership of Sprint Corp. and three large cable-TV companies, owned 49 percent of APC. The Sprint venture was the largest single buyer at a government-run spectrum auction that raised $7.7 billion in 2005 for PCS licenses. APC operated under the brand name of Sprint Spectrum and launched its service on 15 November 1995, in Washington, D.C. and in Baltimore, Maryland. Vice President Al Gore in Washington, D.C. made the initial phone-call to launch the network, calling Mayor Kurt Schmoke in Baltimore.[13]\
Initial growth of text messaging[where?] was slow, with customers in 1995 sending on average only 0.4 messages per GSM customer per month.[14] One factor in the slow take-up of SMS was that operators were slow to set up charging systems, especially for prepaid subscribers, and to eliminate billing fraud, which was possible by changing SMSC settings on individual handsets to use the SMSCs of other operators.[citation needed] Over time, this issue was eliminated by switch billing instead of billing at the SMSC and by new features within SMSCs to allow blocking of foreign mobile users sending messages through it.[citation needed] SMS is available on a wide range of networks, including 3G networks. However, not all text-messaging systems use SMS; some notable alternate implementations of the concept include J-Phones SkyMail and NTT Docomos Short Mail, both in Japan. E-mail messaging from phones, as popularized by NTT Docomos i-mode and the RIM BlackBerry, also typically use standard mail protocols such as SMTP over TCP/IP.[15] As of 2007 text messaging was the most widely used mobile data service, with 74% of all mobile phone users worldwide, or 2.4 billion out of 3.3 billion phone subscribers, at the end of 2007 being active users of the Short Message Service. In countries such as Finland, Sweden, and Norway, over 85% of the population use SMS. The European average is about 80%, and North America is rapidly catching up with over 60% active users of SMS by end of 2008.[citation needed] The largest average usage of the service by mobile phone subscribers occurs in the Philippines, with an average of 27 texts sent per day per subscriber.[citation needed]\
Uses[edit]\
A text message on an iPhone announcing an AMBER Alert\
Text messaging is most often used between private mobile phone users, as a substitute for voice calls in situations where voice communication is impossible or undesirable (e.g., during a school class or a work meeting). Texting is also used to communicate very brief messages, such as informing someone that you will be late or reminding a friend or colleague about a meeting. As with e-mail, informality and brevity have become an accepted part of text messaging. Some text messages such as SMS can also be used for the remote control of home appliances. It is widely used in domotics systems. Some amateurs have also built their own systems to control (some of) their appliances via SMS.[16][17] Other methods such as group messaging, which was patented in 2012 by the GM of Andrew Ferry, Devin Peterson, Justin Cowart, Ian Ainsworth, Patrick Messinger, Jacob Delk, Jack Grande, Austin Hughes, Brendan Blake, and Brooks Brasher are used to involve more than two people into a text messaging conversation[citation needed]. A Flash SMS is a type[18] of text message that appears directly on the main screen without user interaction and is not automatically stored in the inbox. It can be useful in cases such as an emergency (e.g., fire alarm) or confidentiality (e.g., one-time password).[19]\
Short message services are developing very rapidly throughout the world. SMS is particularly popular in Europe, Asia (excluding Japan; see below), United States, Australia, and New Zealand and is also gaining influence in Africa. Popularity has grown to a sufficient extent that the term texting (used as a verb meaning the act of mobile phone users sending short messages back and forth) has entered the common lexicon. Young Asians consider SMS as the most popular mobile phone application.[20] Fifty percent of American teens send fifty text messages or more per day, making it their most frequent form of communication.[21] In China, SMS is very popular and has brought service providers significant profit (18 billion short messages were sent in 2001).[22]\
It is a very influential and powerful tool in the Philippines, where the average user sends 10–12 text messages a day. The Philippines alone sends on average over 1 billion text messages a day,[23] more than the annual average SMS volume of the countries in Europe, and even China and India. SMS is hugely popular in India, where youngsters often exchange many text messages, and companies provide alerts, infotainment, news, cricket scores updates, railway/airline booking, mobile billing, and banking services on SMS.\
Similarly, in 2008, text messaging played a primary role in the implication of former Detroit Mayor Kwame Kilpatrick in an SMS sex scandal.[24] Short messages are particularly popular among young urbanites. In many markets, the service is comparatively cheap. For example, in Australia, a message typically costs between A$0.20 and $0.25 to send (some prepaid services charge $0.01 between their own phones), compared with a voice call, which costs somewhere between $0.40 and $2.00 per minute (commonly charged in half-minute blocks). The service is enormously profitable to the service providers. At a typical length of only 190 bytes (including protocol overhead), more than 350 of these messages per minute can be transmitted at the same data rate as a usual voice call (9 kbit/s). There are also free SMS services available, which are often sponsored, that allow sending[25] and receiving[26] SMS from a PC connected to the Internet. Mobile service providers in New Zealand, such as Vodafone and Telecom NZ, provide up to 2000 SMS messages for NZ$10 per month. Users on these plans send on average 1500 SMS messages every month. Text messaging has become so popular that advertising agencies and advertisers are now jumping into the text messaging business. Services that provide bulk text message sending are also becoming a popular way for clubs, associations, and advertisers to reach a group of opt-in subscribers quickly.\
Research suggests that Internet-based mobile messaging will have grown to equal the popularity of SMS in 2013, with nearly 10 trillion messages being sent through each technology.[27][28] Services such as Facebook Messenger, Snapchat, WhatsApp and Viber have led to a decline in the use of SMS in parts of the world.\
Research has shown that women are more likely than men to use emoticons in text messages.[29]'

In [3]:
text = 'abcdefgh ijk'

In [11]:
len(texts)

30039

In [4]:

chars = tuple(set(texts))
int2char = dict(enumerate(chars))
char2int = {ch: ii for ii, ch in int2char.items()}

# encode the text
encoded = np.array([char2int[ch] for ch in texts])

def one_hot_encode(arr, n_labels):
    
    # Initialize the the encoded array
    one_hot = np.zeros((arr.size, n_labels), dtype=np.float32)
    
    # Fill the appropriate elements with ones
    one_hot[np.arange(one_hot.shape[0]), arr.flatten()] = 1.
    
    # Finally reshape it to get back to the original array
    one_hot = one_hot.reshape((*arr.shape, n_labels))
    
    return one_hot

# check that the function works as expected
test_seq = np.array([[3, 5, 1]])
one_hot = one_hot_encode(test_seq, 10)

print(one_hot)


[[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]]


In [5]:
def get_batches(arr, batch_size, seq_length):
    '''Create a generator that returns batches of size
       batch_size x seq_length from arr.
       
       Arguments
       ---------
       arr: Array you want to make batches from
       batch_size: Batch size, the number of sequences per batch
       seq_length: Number of encoded chars in a sequence
    '''
    
    batch_size_total = batch_size * seq_length
    # total number of batches we can make
    n_batches = len(arr)//batch_size_total
    
    # Keep only enough characters to make full batches
    arr = arr[:n_batches * batch_size_total]
    # Reshape into batch_size rows
    arr = arr.reshape((batch_size, -1))
    
    # iterate through the array, one sequence at a time
    for n in range(0, arr.shape[1], seq_length):
        # The features
        x = arr[:, n:n+seq_length]
        # The targets, shifted by one
        y = np.zeros_like(x)
        try:
            y[:, :-1], y[:, -1] = x[:, 1:], arr[:, n+seq_length]
        except IndexError:
            y[:, :-1], y[:, -1] = x[:, 1:], arr[:, 0]
        yield x, y


In [31]:
a = encoded[:500]
batch = 12
seq = 11
bt = batch * seq
tb = len(a)//bt
b = a[:tb * bt]
b = b.reshape(batch,-1)
b

array([[ 9,  8, 49, 50, 49,  5, 49,  2, 60, 59, 53,  2, 51,  5, 50, 60,
        49,  5, 49, 73, 59, 51, 26,  8, 50, 25,  4, 25, 60, 49, 12, 25,
        70],
       [50, 61, 49, 64, 49,  5, 72, 26, 49, 61, 50, 53,  6, 50, 60,  8,
        49, 50, 49, 51, 59,  5,  4, 50, 20,  0, 60,  8, 50,  2, 49,  6,
        60],
       [63, 59,  4, 70, 50, 63, 25, 49, 61, 50, 25, 53, 12, 26,  5, 49,
        50, 49,  5, 49,  2, 60, 59, 53,  2, 51,  5, 50, 25, 53, 73,  6,
        51],
       [ 5, 25, 50, 60, 72, 50, 25, 49,  6, 61, 50, 60, 49, 18, 60, 50,
        12, 49, 25, 25, 51, 73, 49, 25, 36, 50, 74,  6, 50, 60,  8, 49,
        50],
       [ 5, 51, 60, 49, 50, 20,  0, 60,  8, 50,  2, 49,  6, 60, 63, 59,
         4, 70, 50, 60,  8, 49, 50, 10, 53, 59, 49,  5, 49, 25, 25, 50,
        60],
       [49,  5, 49, 73, 59, 51, 26,  8,  4, 50, 10, 51, 25, 50, 61, 49,
        64, 49,  5, 72, 26, 49, 61, 50, 63, 25, 53,  6, 73, 50, 59, 51,
        61],
       [53, 72, 50, 10, 51, 64, 49, 25, 36, 50, 74,  6, 50

In [35]:
batches = get_batches(a , 12, 11)
#x, y = next(batches)

print(len(a))
print(a[:200])
    
for x, y in batches:
# printing out the first 10 items in a sequence
    print('x\n', x[:, :100])
    print('\ny\n', y[:, :100])

500
[ 9  8 49 50 49  5 49  2 60 59 53  2 51  5 50 60 49  5 49 73 59 51 26  8
 50 25  4 25 60 49 12 25 70 50 61 49 64 49  5 72 26 49 61 50 53  6 50 60
  8 49 50 49 51 59  5  4 50 20  0 60  8 50  2 49  6 60 63 59  4 70 50 63
 25 49 61 50 25 53 12 26  5 49 50 49  5 49  2 60 59 53  2 51  5 50 25 53
 73  6 51  5 25 50 60 72 50 25 49  6 61 50 60 49 18 60 50 12 49 25 25 51
 73 49 25 36 50 74  6 50 60  8 49 50  5 51 60 49 50 20  0 60  8 50  2 49
  6 60 63 59  4 70 50 60  8 49 50 10 53 59 49  5 49 25 25 50 60 49  5 49
 73 59 51 26  8  4 50 10 51 25 50 61 49 64 49  5 72 26 49 61 50 63 25 53
  6 73 50 59 51 61 53 72]
x
 [[ 9  8 49 50 49  5 49  2 60 59 53]
 [50 61 49 64 49  5 72 26 49 61 50]
 [63 59  4 70 50 63 25 49 61 50 25]
 [ 5 25 50 60 72 50 25 49  6 61 50]
 [ 5 51 60 49 50 20  0 60  8 50  2]
 [49  5 49 73 59 51 26  8  4 50 10]
 [53 72 50 10 51 64 49 25 36 50 74]
 [ 2  8 25 26 72 25 60 50  3 67 49]
 [60 59 72 61 63  2 49 61 50 60  8]
 [49 36  9  8 49 50 56  6 53 64 49]
 [63 25 53  6 73 50 59 

In [7]:
batches2 = get_batches(encoded[23640:], 64, 100)
x, y = next(batches2)

# printing out the first 10 items in a sequence
print('x\n', x[:10, :100])
print('\ny\n', y[:10, :100])

StopIteration: 

In [8]:
np.zeros_like(x)

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [74]:
class CharRNN(nn.Module):
    
    def __init__(self, tokens, n_hidden=256, n_layers=2,
                               drop_prob=0.5, lr=0.001):
        super().__init__()
        self.drop_prob = drop_prob
        self.n_layers = n_layers
        self.n_hidden = n_hidden
        self.lr = lr
        
        # creating character dictionaries
        self.chars = tokens
        self.int2char = dict(enumerate(self.chars))
        self.char2int = {ch: ii for ii, ch in self.int2char.items()}
        
        ## TODO: define the LSTM
        self.lstm = nn.LSTM(len(self.chars), n_hidden, n_layers, 
                            dropout=drop_prob, batch_first=True)
        
        ## TODO: define a dropout layer
        self.dropout = nn.Dropout(drop_prob)
        
        ## TODO: define the final, fully-connected output layer
        self.fc = nn.Linear(n_hidden, len(self.chars))
      
    
    def forward(self, x, hidden):
        ''' Forward pass through the network. 
            These inputs are x, and the hidden/cell state `hidden`. '''
                
        ## TODO: Get the outputs and the new hidden state from the lstm
        r_output, hidden = self.lstm(x, hidden)
        
        ## TODO: pass through a dropout layer
        out = self.dropout(r_output)
        
        # Stack up LSTM outputs using view
        # you may need to use contiguous to reshape the output
        out = out.contiguous().view(-1, self.n_hidden)
        
        ## TODO: put x through the fully-connected layer
        out = self.fc(out)
        
        # return the final output and the hidden state
        return out, hidden
    
    
    def init_hidden(self, batch_size):
        ''' Initializes hidden state '''
        # Create two new tensors with sizes n_layers x batch_size x n_hidden,
        # initialized to zero, for hidden state and cell state of LSTM
        weight = next(self.parameters()).data
        
        #if (train_on_gpu):
        #    hidden = (weight.new(self.n_layers, batch_size, self.n_hidden).zero_().cuda(),
        #          weight.new(self.n_layers, batch_size, self.n_hidden).zero_().cuda())
        #else:
        hidden = (weight.new(self.n_layers, batch_size, self.n_hidden).zero_(),
                  weight.new(self.n_layers, batch_size, self.n_hidden).zero_())
        print('h initiallllllllllllllllllllllllllllllllllllllllll 1 tuple:', hidden[0].shape)
        print('h initiallllllllllllllllllllllllllllllllllllllllll 2 tuple:', hidden[1].shape)
        
        return hidden


In [91]:
def train(net, data, epochs=10, batch_size=10, seq_length=50, lr=0.001, clip=5, val_frac=0.15, print_every=1):
    ''' Training a network 
    
        Arguments
        ---------
        
        net: CharRNN network
        data: text data to train the network
        epochs: Number of epochs to train
        batch_size: Number of mini-sequences per mini-batch, aka batch size
        seq_length: Number of character steps per mini-batch
        lr: learning rate
        clip: gradient clipping
        val_frac: Fraction of data to hold out for validation
        print_every: Number of steps for printing training and validation loss
    
    '''
    net.train()
    
    opt = torch.optim.Adam(net.parameters(), lr=lr)
    criterion = nn.CrossEntropyLoss()
    
    # create training and validation data
    val_idx = int(len(data)*(1-val_frac))
    data, val_data = data[:val_idx], data[val_idx:]
    
    #if(train_on_gpu):
    #    net.cuda()
    
    counter = 0
    n_chars = len(net.chars)
    for e in range(epochs):
        # initialize hidden state
        h = net.init_hidden(batch_size)
        #x, y = get_batches(data, batch_size, seq_length)
        for x, y in get_batches(data, batch_size, seq_length):
            counter += 1
            # One-hot encode our data and make them Torch tensors
            x = one_hot_encode(x, n_chars)
            inputs, targets = torch.from_numpy(x), torch.from_numpy(y)
            
            #if(train_on_gpu):
            #    inputs, targets = inputs.cuda(), targets.cuda()

            # Creating new variables for the hidden state, otherwise
            # we'd backprop through the entire training history
            h = tuple([each.data for each in h])

            # zero accumulated gradients
            net.zero_grad()
            
            # get the output from the model
            output, h = net(inputs, h)
            
            # calculate the loss and perform backprop
            loss = criterion(output, targets.view(batch_size*seq_length).long())
            loss.backward()
            # `clip_grad_norm` helps prevent the exploding gradient problem in RNNs / LSTMs.
            nn.utils.clip_grad_norm_(net.parameters(), clip)
            opt.step()
            
            # loss stats
            if counter % print_every == 0:
                # Get validation loss
                val_h = net.init_hidden(batch_size)
                val_losses = []
                net.eval()
                print(val_data.shape, batch_size, seq_length)
                for x, y in get_batches(val_data, batch_size, seq_length):
                    # One-hot encode our data and make them Torch tensors
                    x = one_hot_encode(x, n_chars)
                    inputs, targets = torch.from_numpy(x), torch.from_numpy(y)
                    
                    # Creating new variables for the hidden state, otherwise
                    # we'd backprop through the entire training history
                    val_h = tuple([each.data for each in val_h])
                    
                    #inputs, targets = x, y
                    #if(train_on_gpu):
                    #    inputs, targets = inputs.cuda(), targets.cuda()

                    output, val_h = net(inputs, val_h)
                    val_loss = criterion(output, targets.view(batch_size*seq_length).long())
                
                    val_losses.append(val_loss.item())
                
                net.train() # reset to train mode after iterationg through validation data
                
                print("Epoch: {}/{}...".format(e+1, epochs),
                      "Step: {}...".format(counter),
                      "Loss: {:.4f}...".format(loss.item()),
                      "Val Loss: {:.4f}".format(np.mean(val_losses)))

In [92]:
# define and print the net
n_hidden=512
n_layers=3

net = CharRNN(chars, n_hidden, n_layers)
print(net)

batch_size = 20
seq_length = 50
n_epochs = 2 # start smaller if you are just testing initial behavior

# train the model
train(net, encoded, epochs=n_epochs, batch_size=batch_size, seq_length=seq_length, lr=0.001, print_every=10)


CharRNN(
  (lstm): LSTM(76, 512, num_layers=3, batch_first=True, dropout=0.5)
  (dropout): Dropout(p=0.5, inplace=False)
  (fc): Linear(in_features=512, out_features=76, bias=True)
)
h initiallllllllllllllllllllllllllllllllllllllllll 1 tuple: torch.Size([3, 20, 512])
h initiallllllllllllllllllllllllllllllllllllllllll 2 tuple: torch.Size([3, 20, 512])
h initiallllllllllllllllllllllllllllllllllllllllll 1 tuple: torch.Size([3, 20, 512])
h initiallllllllllllllllllllllllllllllllllllllllll 2 tuple: torch.Size([3, 20, 512])
(4506,) 20 50
Epoch: 1/2... Step: 10... Loss: 3.2798... Val Loss: 3.2353
h initiallllllllllllllllllllllllllllllllllllllllll 1 tuple: torch.Size([3, 20, 512])
h initiallllllllllllllllllllllllllllllllllllllllll 2 tuple: torch.Size([3, 20, 512])
(4506,) 20 50
Epoch: 1/2... Step: 20... Loss: 3.2196... Val Loss: 3.2134
h initiallllllllllllllllllllllllllllllllllllllllll 1 tuple: torch.Size([3, 20, 512])
h initiallllllllllllllllllllllllllllllllllllllllll 2 tuple: torch.Size([3, 2

In [47]:
def predict(net, char, h=None, top_k=None):
        ''' Given a character, predict the next character.
            Returns the predicted character and the hidden state.
        '''
        
        # tensor inputs
        x = np.array([[net.char2int[char]]])
        x = one_hot_encode(x, len(net.chars))
        inputs = torch.from_numpy(x)
        
        #if(train_on_gpu):
        #    inputs = inputs.cuda()
        
        # detach hidden state from history
        h = tuple([each.data for each in h])
        # get the output of the model
        out, h = net(inputs, h)

        # get the character probabilities
        p = F.softmax(out, dim=1).data
        #if(train_on_gpu):
        #    p = p.cpu() # move to cpu
        
        # get top characters
        if top_k is None:
            top_ch = np.arange(len(net.chars))
        else:
            p, top_ch = p.topk(top_k)
            top_ch = top_ch.numpy().squeeze()
        
        # select the likely next character with some element of randomness
        p = p.numpy().squeeze()
        char = np.random.choice(top_ch, p=p/p.sum())
        
        # return the encoded value of the predicted char and the hidden state
        return net.int2char[char], h


In [35]:
def sample(net, size, prime='The', top_k=None):
        
    #if(train_on_gpu):
    #    net.cuda()
    #else:
    #    net.cpu()
    
    net.eval() # eval mode
    
    # First off, run through the prime characters
    chars = [ch for ch in prime]
    h = net.init_hidden(1)
    for ch in prime:
        char, h = predict(net, ch, h, top_k=top_k)

    chars.append(char)
    
    # Now pass in the previous character and get a new one
    for ii in range(size):
        char, h = predict(net, chars[-1], h, top_k=top_k)
        chars.append(char)

    return ''.join(chars)

print(sample(net, 2000, prime='In ', top_k=75))


In cawtits user syithar moilenging asared on the an libling as ef SoS mat sanined fo sete an teet. centang as a wort messing os in is bla lebt user berring in the elilt in bipling on a corme cabce subs an Averipe prosided the first text-messaging service in the Ui te the Uu hed SM  an the GMU fed the rISMgu lentirg on imiill oseydang for moicil pessing sublion Kore, and ranle coblane Tor pompiniles sich an Finlard, Sweden, and Norway, over 85% ofver op operinale worepess in 1994. When Radiolinjas domestic competitor, Telecom Finland (now part of Teerrag sy secotol ussor wuy to send migite network is ofher SM. an the GMU oserd Averite in Avericay 19th century, the wireles telegraphy was developed using radios sath ressing to cobtrol an the elin text messaging. Text messagisg is use sady nat of Speves Spnute Spéchine Telicome the sagile betwa suiverg badio the first netiol to her SMS text messaging is usually messaging from one mobile phone as a punttricon us netw loth a cartinn cert set

In [124]:
encoded

array([22, 24, 70, ..., 13, 41, 38])

In [67]:
loss = nn.CrossEntropyLoss()
input = torch.randn(3, 5, requires_grad=True)
target = torch.empty(3, dtype=torch.long).random_(5)
output = loss(input, target)
output.backward()

In [68]:
input.shape

torch.Size([3, 5])

In [69]:
target.shape

torch.Size([3])

In [70]:
input

tensor([[-0.4192, -0.7465, -0.1437,  0.0296,  0.3515],
        [-0.6168,  0.1202,  0.6278, -0.3241, -0.0210],
        [-2.1664,  0.9830, -0.3004, -0.1873, -1.0456]], requires_grad=True)

In [71]:
target

tensor([1, 2, 2])

In [72]:
output

tensor(1.7060, grad_fn=<NllLossBackward>)